### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by wesbos** [jlkiri/gatsby-remark-shiki#1]
Hey - thanks for making this! I'm not able to get this working. I'm using `gatsby-plugin-mdx` and have tried under gatsbyRemarkPlugins as well as under `gatsby-transformer-remark` plugins. Neither do anything. 

I see this is relatively new - should this be working already?

**Comment by jlkiri** [comment]
Hey! Thanks for using this. This should definitely work with `gatsby-transformer-remark` (tested on this starter: https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-blog/). Although note that it supports less languages than Prism (e.g. Haskell is not supported, but Javascript is OK)

However, I never tried it with `gatsby-plugin-mdx`. It could be their issue, but I'll check it.

**Comment by jlkiri** [comment]
@wesbos Turns out it was 2 bugs. One of them is my bug and the other one is the bug in `gatsby-plugin-mdx`. I fixed mine in `v0.1.2` but it still won't work for you until `gatsby-plugin-mdx` is fixed. Here is the issue that you can monitor: https://github.com/gatsbyjs/gatsby/issues/21821

**Comment by wesbos** [comment]
thank you so much! Going to monitor that issue :D

**Comment by jlkiri** [comment]
@wesbos ~~Should work in `gatsby@2.19.24`.~~ Waiting for release.

**Comment by jlkiri** [comment]
@wesbos Should work in `gatsby-plugin-mdx@1.0.75`. Don't forget to also update `gatsby-remark-shiki` to `0.1.2`!
https://github.com/gatsbyjs/gatsby/releases/tag/gatsby-plugin-mdx%401.0.75
